### PR TITLE
Fix compilation

### LINKED ISSUE #5: Can't install on MacOS 13.5.2
Towards the end of the install using "cargo binstall nu-completion-script", I get the following error causing it to error out. I'm running MacOS 13.5.2 on M1 with rustc 1.72.0 if that helps at all. 

Please let me know if there are any log files that I can provide to help further!

**Skipping the lines from binstall, and going to errors:**
```
...
   Compiling reqwest v0.11.20
   Compiling nu-completion-script v0.1.3
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nu-completion-script-0.1.3/src/main.rs:1:1
  |
1 | #![feature(once_cell, never_type, exit_status_error, async_closure, let_chains)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'lazy_cell'
  --> /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nu-completion-script-0.1.3/src/main.rs:15:5
   |
15 |     sync::LazyLock,
   |     ^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nu-completion-script-0.1.3/src/main.rs:76:24
   |
76 |     static CONFIG_DEF: LazyLock<String> =
   |                        ^^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nu-completion-script-0.1.3/src/main.rs:77:9
   |
77 | ...   LazyLock::new(|| format!("source {:?}", Config::imports_location()));
   |       ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
 --> /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nu-completion-script-0.1.3/src/config.rs:5:5
  |
5 |     sync::LazyLock,
  |     ^^^^^^^^^^^^^^
  |
  = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nu-completion-script-0.1.3/src/config.rs:95:20
   |
95 | pub static CONFIG: LazyLock<Config> = LazyLock::new(Config::parse);
   |                    ^^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nu-completion-script-0.1.3/src/config.rs:95:39
   |
95 | pub static CONFIG: LazyLock<Config> = LazyLock::new(Config::parse);
   |                                       ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
 --> /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nu-completion-script-0.1.3/src/nu.rs:8:12
  |
8 |     sync::{LazyLock, RwLock},
  |            ^^^^^^^^
  |
  = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
   --> /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nu-completion-script-0.1.3/src/nu.rs:275:22
    |
275 | static INDENT_CACHE: LazyLock<RwLock<Vec<String>>> = LazyLock::new(|| R...
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
   --> /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nu-completion-script-0.1.3/src/nu.rs:275:54
    |
275 | static INDENT_CACHE: LazyLock<RwLock<Vec<String>>> = LazyLock::new(|| R...
    |                                                      ^^^^^^^^
    |
    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nu-completion-script-0.1.3/src/main.rs:1:12
  |
1 | #![feature(once_cell, never_type, exit_status_error, async_closure, let_c...
  |            ^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nu-completion-script-0.1.3/src/main.rs:1:35
  |
1 | #![feature(once_cell, never_type, exit_status_error, async_closure, let_c...
  |                                   ^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'lazy_cell'
  --> /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nu-completion-script-0.1.3/src/main.rs:77:9
   |
77 | ...   LazyLock::new(|| format!("source {:?}", Config::imports_location()));
   |       ^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nu-completion-script-0.1.3/src/config.rs:95:39
   |
95 | pub static CONFIG: LazyLock<Config> = LazyLock::new(Config::parse);
   |                                       ^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
   --> /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nu-completion-script-0.1.3/src/nu.rs:275:54
    |
275 | static INDENT_CACHE: LazyLock<RwLock<Vec<String>>> = LazyLock::new(|| R...
    |                                                      ^^^^^^^^^^^^^
    |
    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

Some errors have detailed explanations: E0554, E0658.
For more information about an error, try `rustc --explain E0554`.
error: could not compile `nu-completion-script` (bin "nu-completion-script") due to 15 previous errors
error: failed to compile `nu-completion-script v0.1.3`, intermediate artifacts can be found at `/var/folders/jq/jnw70_td671fdvqt9w41w6r00000gn/T/cargo-install0eMOnd`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
ERROR Cargo errored! ExitStatus(unix_wait_status(25856))
ERROR Fatal error:
binstall::subprocess

  × subprocess /opt/homebrew/Cellar/rust/1.72.0_1/bin/cargo install nu-
  │ completion-script --version 0.1.3 --target aarch64-apple-darwin errored
  │ with exit status: 101
```

### PR DESCRIPTION
**Pull request by gierens**
This adds the missing `lazy_cell` feature to the required features in `main.rs` and also updates the `Cargo.lock` to make compilation work with rust 1.74 nightly.

Fixes #5

### CODE REVIEW

**Comment by dscottboggs** [comment]
Would you consider instead maintaining a fork, as suggested in [this note](https://github.com/dscottboggs/nu-completions#moving-on) in the README?

**Comment by gierens** [comment]
Hey @dscottboggs , sorry for getting back to you so late ... have been a little busy lately. 

Hm, as it happens I actually created an organization for adopting unmaintained rust crates a while back (https://github.com/rustadopt) ... So, we could "adopt" it there. Usually we copy the complete project instead of forking though.

**Comment by dscottboggs** [comment]
That's fine with me. I understand there's some interest in this, but I really feel like it's a dead end and would rather cut it loose through whatever means possible.
